route:
  group_by: ['alertname']
  receiver: 'wechat'
  repeat_interval: 60m

receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: 'your_corp_id'
    to_party: '2'
    agent_id: '1'
    api_secret: 'your_api_secret'

